services:
  redis:
    image: redis:7.2-alpine
    container_name: makeit3d-bff-redis
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: makeit3d-bff-backend
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./app:/app  # Mount the app directory to /app inside the container for hot-reloading
    ports:
      - "8000:8000"
    environment:
      # Pass environment variables to the backend service
      # In a real scenario, use a proper secrets management solution
      - TRIPO_API_KEY=${TRIPO_API_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - STABILITY_API_KEY=${STABILITY_API_KEY}
      - RECRAFT_API_KEY=${RECRAFT_API_KEY}
      - REPLICATE_API_KEY=${REPLICATE_API_KEY}
      - FLUX_API_KEY=${FLUX_API_KEY}
      - REGISTRATION_SECRET=${REGISTRATION_SECRET}
      - DATABASE_URL=${DATABASE_URL}
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_SERVICE_KEY=${SUPABASE_SERVICE_KEY}
      - REDIS_URL=redis://redis:6379/0 # Redis service name as hostname
      - BFF_BASE_URL=${BFF_BASE_URL:-http://localhost:8000}
      - TEST_ASSETS_MODE=${TEST_ASSETS_MODE:-False}
    depends_on:
      - redis

  celery_worker_default:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: makeit3d-bff-celery_default_worker
    command: celery -A celery_worker worker -l info -P eventlet -c 1 -Q default
    volumes:
      - ./app:/app
    environment:
      - TRIPO_API_KEY=${TRIPO_API_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - STABILITY_API_KEY=${STABILITY_API_KEY}
      - RECRAFT_API_KEY=${RECRAFT_API_KEY}
      - REPLICATE_API_KEY=${REPLICATE_API_KEY}
      - FLUX_API_KEY=${FLUX_API_KEY}
      - REGISTRATION_SECRET=${REGISTRATION_SECRET}
      - DATABASE_URL=${DATABASE_URL}
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_SERVICE_KEY=${SUPABASE_SERVICE_KEY}
      - REDIS_URL=redis://redis:6379/0
      - BFF_BASE_URL=${BFF_BASE_URL:-http://localhost:8000}
      - TEST_ASSETS_MODE=${TEST_ASSETS_MODE:-False}
    depends_on:
      - redis

  celery_worker_tripo_other:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: makeit3d-bff-celery_tripo_other_worker
    command: celery -A celery_worker worker -l info -P eventlet -c 10 -Q tripo_other_queue
    volumes:
      - ./app:/app
    environment:
      - TRIPO_API_KEY=${TRIPO_API_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - STABILITY_API_KEY=${STABILITY_API_KEY}
      - RECRAFT_API_KEY=${RECRAFT_API_KEY}
      - REPLICATE_API_KEY=${REPLICATE_API_KEY}
      - FLUX_API_KEY=${FLUX_API_KEY}
      - REGISTRATION_SECRET=${REGISTRATION_SECRET}
      - DATABASE_URL=${DATABASE_URL}
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_SERVICE_KEY=${SUPABASE_SERVICE_KEY}
      - REDIS_URL=redis://redis:6379/0
      - BFF_BASE_URL=${BFF_BASE_URL:-http://localhost:8000}
      - TEST_ASSETS_MODE=${TEST_ASSETS_MODE:-False}
    depends_on:
      - redis

  celery_worker_tripo_refine:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: makeit3d-bff-celery_tripo_refine_worker
    command: celery -A celery_worker worker -l info -P eventlet -c 5 -Q tripo_refine_queue
    volumes:
      - ./app:/app
    environment:
      - TRIPO_API_KEY=${TRIPO_API_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - STABILITY_API_KEY=${STABILITY_API_KEY}
      - RECRAFT_API_KEY=${RECRAFT_API_KEY}
      - REPLICATE_API_KEY=${REPLICATE_API_KEY}
      - FLUX_API_KEY=${FLUX_API_KEY}
      - REGISTRATION_SECRET=${REGISTRATION_SECRET}
      - DATABASE_URL=${DATABASE_URL}
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_SERVICE_KEY=${SUPABASE_SERVICE_KEY}
      - REDIS_URL=redis://redis:6379/0
      - BFF_BASE_URL=${BFF_BASE_URL:-http://localhost:8000}
      - TEST_ASSETS_MODE=${TEST_ASSETS_MODE:-False}
    depends_on:
      - redis

volumes:
  redis_data: 